version: "3.8"

services:
  frontend:
    container_name: argus-vehicle-inventory-frontend
    image: node:16.16.0-alpine
    working_dir: /usr/src/app
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    environment:
      REACT_APP_MAPBOX_TOKEN: ${REACT_APP_MAPBOX_TOKEN}
      REACT_APP_BACKEND_API_URL: ${REACT_APP_BACKEND_API_URL}

  backend:
    container_name: argus-vehicle-inventory-backend
    image: node:16.16.0-alpine
    working_dir: /usr/src/app
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3333:3333
    depends_on:
      - mongodb
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_USER: ${MONGODB_APP_USER}
      DB_PASS: ${MONGODB_APP_PASS}
      DB_NAME: ${MONGODB_APP_DBNAME}

  mongodb:
    container_name: argus-vehicle-inventory-mongodb
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./provision/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASS}
      MONGODB_APP_USER: ${MONGODB_APP_USER}
      MONGODB_APP_PASS: ${MONGODB_APP_PASS}
      MONGODB_APP_DBNAME: ${MONGODB_APP_DBNAME}

volumes:
  mongodb_data:
  mongodb_config:
