services:
  frontend:
    container_name: argus-vehicle-inventory-frontend
    image: node:16.16.0-alpine
    working_dir: /usr/src/app
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000

  backend:
    container_name: argus-vehicle-inventory-backend
    image: node:16.16.0-alpine
    working_dir: /usr/src/app
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3333:3333
    depends_on:
      - mongodb

  mongodb:
    container_name: argus-vehicle-inventory-mongodb
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123!@#